version: 2
jobs:
  build:
    docker:
      - image: circleci/node:boron
    working_directory: ~/vtt2srt
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ checksum "yarn.lock" }}
      - run: yarn test
